{{- if not (kindIs "slice" .Values.secrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devjams-deployment.fullname" . }}-secrets
  labels:
    {{- include "devjams-deployment.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
{{- end }}
{{- end }}
